from pydantic import BaseModel, Field

class Pokemon(BaseModel):
    """
    Represents a single Pokémon.
    """
    id: int
    name: str = Field(..., min_length=1, description="The name of the Pokémon.")
    type: str = Field(..., min_length=1, description="The type of the Pokémon (e.g., Fire, Water).")

class PokemonCreate(BaseModel):
    """
    Represents the data required to create a new Pokémon.
    ID is not included as it will be generated by the system.
    """
    name: str = Field(..., min_length=1, description="The name of the Pokémon.")
    type: str = Field(..., min_length=1, description="The type of the Pokémon (e.g., Fire, Water).")
